# Setting my preferred default editor
EDITOR=vim # Command line uses 'vim'
VISUAL=mvim # Visual editor is MacVim
GIT_EDITOR=vim # Editor for Git
export EDITOR VISUAL GIT_EDITOR # Export these options

alias ls="ls -la -Gp -F"        # Make 'ls' do lotsa stuff
alias reload!="source ~/.zshrc" # Make 'reload!' source the .zshrc file
alias sudo="sudo "              # Fix using aliases after sudo
alias eduan="cd ~/Desktop/Eduan"

# Initialize colors.
autoload -U colors
colors

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# Load settings for Git prompt
source ~/.zsh/vcs-prompt.sh

# Load Git prompt
source ~/.zsh/zsh-vcs-prompt/zshrc.sh

# Set the prompt
PROMPT=$'%{${fg[green]}%}%n@%m:'  # Green color, current user@server
PROMPT+='%{${fg[blue]}%}%~'       # Blue color, current directory, from $HOME
PROMPT+='%{${fg[default]}%}$(vcs_super_info)' # Default color, Git status
PROMPT+='%{${fg[default]}%} $ ' # Default color, prompt

# Set the right side of my prompt
RPROMPT=$'$(acpi | grep -o \'[0-9]*%\')% %T' # Default color, time

# Some history settings
HISTSIZE=1000       # The size of the history of current shell
SAVEHIST=1000       # The size of the history that it's gonna save in a file
HISTFILE=~/.history # This file where to save the history
export HIST_IGNORE_ALL_DUPS # Ignore all duplicates and usual commands

# http://stackoverflow.com/q/12247777/1622940
export PROMPT_COMMAND="history -a; history -n"

# vim: set foldmarker={{{,}}}
