# Kudos and credits to this blog, for providing a way to have a prompt the
# current Git branch in a fancy way:
# http://sebastiancelis.com/2009/11/16/zsh-prompt-git-users/

# Initialize colors
autoload -U colors && colors

# Allow for functions in the prompt
setopt PROMPT_SUBST

# Autoload zsh functions
fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

# Enable auto-execution of functions
typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions

alias ls="ls -la -Gp -F"
alias gvim="mvim --remote-silent"

# Append git functions needed for prompt
preexec_functions+='preexec_update_git_vars'
precmd_functions+='precmd_update_git_vars'
chpwd_functions+='chpwd_update_git_vars'

# Set the prompt
PROMPT=$'%{${fg[yellow]}%}[%T] %{${fg[cyan]}%}%~$(prompt_git_info)%{${fg[default]}%} >>> '
RPROMPT=$'%{${fg[default]}%}[%n@%m]'
