# Sources {{{1

# Editor {{{1

# Setting my preferred default editor
EDITOR=vim  # Command line uses 'vim'
VISUAL=mvim # Visual editor is MacVim
export EDITOR VISUAL # Export both these options

# Aliases {{{1

alias ls="ls -la -Gp -F"          # Make 'ls' do lotsa stuff 
alias gvim="mvim --remote-silent" # Make 'gvim' not open a new MacVim window
alias reload!="source ~/.zshrc"   # Make 'reload!' source the .zshrc file

# $PATH stuff {{{1

# Enable loading of MySQL
export PATH="/usr/local/mysql/bin:$PATH"

# Prompt {{{1

# Initialize colors.
autoload -U colors
colors

# Allow for functions in the prompt.
setopt PROMPT_SUBST

# VCS prompt configuration {{{2

# Git.
ZSH_VCS_PROMPT_GIT_FORMATS=' (%s)[%b%c%d|%e%f%g%h%i%j]'
ZSH_VCS_PROMPT_GIT_ACTION_FORMATS=' (%s)[%b:%a%c%d|%e%f%g%h%i%j]'
# Other vcs.
ZSH_VCS_PROMPT_VCS_FORMATS=' (%s)[%b]'
ZSH_VCS_PROMPT_VCS_ACTION_FORMATS=' (%s)[%b:%a]'

## The symbols.
ZSH_VCS_PROMPT_AHEAD_SIGIL='↑'
ZSH_VCS_PROMPT_BEHIND_SIGIL='↓'
ZSH_VCS_PROMPT_STAGED_SIGIL='●'
ZSH_VCS_PROMPT_CONFLICTS_SIGIL='✖'
ZSH_VCS_PROMPT_UNSTAGED_SIGIL='✚'
ZSH_VCS_PROMPT_UNTRACKED_SIGIL='…'
ZSH_VCS_PROMPT_STASHED_SIGIL='⚑'
ZSH_VCS_PROMPT_CLEAN_SIGIL='✔'

# }}}2

# Load Git prompt
source ~/.zsh/zsh-vcs-prompt/zshrc.sh

# Set the prompt
PROMPT=$'%{${fg[yellow]}%}[%T] '  # Yellow color, current time
PROMPT+='%{${fg[cyan]}%}%~'       # Cyan color, current directory, from $HOME
PROMPT+='%{${fg[default]}%}$(vcs_super_info)' # Default color, Git status
PROMPT+='%{${fg[default]}%} >>> ' # Default color, prompt

# Set the right side of my prompt
RPROMPT=$'%{${fg[default]}%}[%n' # Default color, current user
RPROMPT+='@%m]' # Current server

# History {{{1

HISTSIZE=1000       # The size of the history of current shell
SAVEHIST=1000       # The size of the history that it's gonna save in a file
HISTFILE=~/.history # This file where to save the history
export HIST_IGNORE_ALL_DUPS # Ignore all duplicates and usual commands

# }}}1

# vim: set foldmarker={{{,}}}
